### ISSUE TITLE
Motion photos don't get uploaded as motion photo

### ISSUE THREAD

**Issue by viktordd** [simulot/immich-go#303] opened 2024-06-15 23:14 UTC
I imported motion photos from Google Takeout via immich-go. The motion photos are displayed as just photos on Immich.

Command used for import
`immich-go -server http://xxx:2283 -key xxx -no-ui -log-file=./immich-go_$(date '+%Y-%m-%d_%H-%M-%S').log upload -create-albums -google-photos ./takeout-motion-test.zip`

Attached sample takeout
[takeout-motion-test.zip](https://github.com/user-attachments/files/15855576/takeout-motion-test.zip)

Also filed an issue with immich since I don't see motion photos in the app either before uploading
https://github.com/immich-app/immich/issues/10374

immich-go v0.17.1
immich v1.106.4

**Comment by simulot** [comment] 2024-06-16 08:23
Thank you for sharing samples.
Its a duplicate of  #280

**Closed** 2024-06-23 17:21 UTC
