### ISSUE TITLE
immich-go import seems to finish early?

### ISSUE THREAD

**Issue by williamkray** [simulot/immich-go#417] opened 2024-07-31 17:36 UTC
executing immich-go to import google takeout archives seems to work fine, however the process consistently stops and says "Upload completed" after only processing through about 75% of the content.

Multiple subsequent runs of the program processes the files again, generally finding that most of the files have already been handled, but i'm getting about 30 more files uploaded each time, again each run stops around 75-80% complete.

running on pop_os linux, v 0.20.1. i only realized this was an issue because i saw other comments on the immich subreddit saying the same thing.

**Comment by williamkray** [comment] 2024-07-31 18:49
example of one of my recent runs (this is the 5th or 6th time i've run the same import command):

![image](https://github.com/user-attachments/assets/2878a4d6-2791-442c-ba25-7b1faced8037)

**Comment by simulot** [comment] 2024-07-31 19:48
This is almost fixed with version 0.21

**Closed as completed** 2024-08-01 15:36 UTC

**Comment by driftywinds** [comment] 2024-08-02 04:11
> This is almost fixed with version 0.21

I know this has been fixed but could you tell me what the problem behind this behaviour was?

**Comment by simulot** [comment] 2024-08-02 07:12
The problem was caused by the difficulty to count how many file among the those scanned need to be uploaded. There are duplicates of many kinds, lives photo + video that count for 2 files, but one upload, files that are already on the server ... etc...

So the 100% of files is definitively not the total of scanned files. 
In your case, all files to be uploaded was representing 75% of the number of files that system had the intention to upload.
I hope I get it right this time.
